DeckOfCardsLab/Models/BrandNewDeckApi.cs
namespace DeckOfCardsLab.Models
{
    public class BrandNewDeckApi
    {
        public bool Success { get; set; }
        public string Deck_id { get; set; }
        public bool Shuffled { get; set; }
        public int Remaining { get; set; }

    }
}

DeckOfCardsLab/Models/Card.cs
namespace DeckOfCardsLab.Models
{
    public class Card
    {
        public string Code { get; set; }
        public string Image {  get; set; }
        public Images Images { get; set; }
        public string Value { get; set; }
        public string Suit { get; set; }

    }
}

DeckOfCardsLab/Models/CardsToDeal.cs
namespace DeckOfCardsLab.Models
{
    public class CardsToDeal
    {
        public int Count { get; set; }
    }
}

DeckOfCardsLab/Models/DrawACardApi.cs
using Newtonsoft.Json;

namespace DeckOfCardsLab.Models
{
    //[JsonObject(MemberSerialization = MemberSerialization.OptIn)]

    public class DrawACardApi
    {
        //[JsonProperty(PropertyName = "Success")]
        public bool Success { get; set; }
        //[JsonProperty(PropertyName = "Deck_Id")]
        public string Deck_Id { get; set; }
        //[JsonProperty(PropertyName = "Cards")]
        public List<Card> Cards { get; set; }
        //[JsonProperty(PropertyName = "Remaining")]
        public int Remaining { get; set; }


    }
}

DeckOfCardsLab/Models/ErrorViewModel.cs
namespace DeckOfCardsLab.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DeckOfCardsLab/Models/Images.cs
namespace DeckOfCardsLab.Models
{
    public class Images
    {
        public string Svg { get; set; }
        public string Png { get; set; }
    }
}

DeckOfCardsLab/Controllers/CardController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Flurl.Http;
using DeckOfCardsLab.Models;
using Newtonsoft;

namespace DeckOfCardsLab.Controllers
{
    public class CardController : Controller
    {
        public IActionResult DrawCards()
        {
            string uri = "https://deckofcardsapi.com/api/deck/new/shuffle/?deck_count=1";
            var apiDeckTask = uri.GetJsonAsync<BrandNewDeckApi>();
            apiDeckTask.Wait();
            BrandNewDeckApi deck = apiDeckTask.Result;

            uri = $"https://deckofcardsapi.com/api/deck/{deck.Deck_id}/draw/?count=5";
            var apiDrawTask = uri.GetJsonAsync<DrawACardApi>();
            apiDrawTask.Wait();
            DrawACardApi cards = apiDrawTask.Result;
            return View(cards.Cards);
        }
    }
}

DeckOfCardsLab/Controllers/HomeController.cs
using DeckOfCardsLab.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DeckOfCardsLab.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DeckOfCardsLab/Views/Card/DrawCards.cshtml
@model IEnumerable<DeckOfCardsLab.Models.Card>

@*@model IEnumerable<DeckOfCardsApi.Models.Card>*@


@{
    ViewData["Title"] = "Draw Cards";
}

<h1>Your 5 Cards!</h1>

<p>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Value)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Suit)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                    <img src="@Html.Raw(item.Image)" alt="HaHa Nice Try!">

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Suit)
            </td>
            <td>
            </td>
        </tr>
}
    </tbody>
</table>

DeckOfCardsLab/Views/Card/Index.cshtml
@model DeckOfCardsLab.Models.CardsToDeal

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<h4>CardsToDeal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DrawCards">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Count" class="control-label"></label>
                <input asp-for="Count" class="form-control" />
                <span asp-validation-for="Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="DrawCards" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DeckOfCardsLab/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DeckOfCardsLab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DeckOfCardsLab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DeckOfCardsLab.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DeckOfCardsLab</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Card" asp-action="DrawCards">Draw Cards</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DeckOfCardsLab - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>